In [1]:
import certifi
import urllib3
import json
from pandas.io.json import json_normalize

In [2]:
http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED',ca_certs=certifi.where())
r = http.request('GET', 'http://hoyodecrimen.com/api/v1/cuadrantes/all/crimes/all/period')
r.status
response = r.data

In [3]:
str_response = response.decode('utf-8')
y = json.loads(str_response)
y = y['rows']

In [4]:
json_normalize(y)

,count,crime,cuadrante,end_date,population,sector,start_date
0,0,HOMICIDIO DOLOSO,C-1.1.1,2019-12,36.0,REVOLUCION-ALAMEDA,2019-01
1,1,HOMICIDIO DOLOSO,C-1.1.2,2019-12,729.0,CORREDOR-CENTRO,2019-01
2,2,HOMICIDIO DOLOSO,C-1.1.3,2019-12,811.0,CORREDOR-CENTRO,2019-01
3,0,HOMICIDIO DOLOSO,C-1.1.4,2019-12,4116.0,MIXCALCO-HERALDO,2019-01
4,1,HOMICIDIO DOLOSO,C-1.1.6,2019-12,4141.0,REVOLUCION-ALAMEDA,2019-01
...,...,...,...,...,...,...,...
16954,1,VIOLACION,S-3.6.4,2019-12,8385.0,PADIERNA,2019-01
16955,4,VIOLACION,S-3.6.5,2019-12,13223.0,PADIERNA,2019-01
16956,0,VIOLACION,S-3.6.6,2019-12,16368.0,PADIERNA,2019-01
16957,3,VIOLACION,S-3.6.7,2019-12,43142.0,PADIERNA,2019-01
16958,3,VIOLACION,S-3.6.8,2019-12,47637.0,PADIERNA,2019-01